=== Robi07/monopolybb/trunk/MonopolyUI/src/configuration/MonopolySchema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (x64) (http://www.altova.com) by ibd (none) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GameBoard">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="CellBase" type="CellBase"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="City">
		<xs:complexContent>
			<xs:extension base="CellBase">
				<xs:sequence>
					<xs:element name="SingleHousePrice" type="xs:int"/>
					<xs:element name="HouseToll">
						<xs:complexType>
							<xs:all>
								<xs:element name="One" type="xs:int"/>
								<xs:element name="Two" type="xs:int"/>
								<xs:element name="Three" type="xs:int"/>
							</xs:all>
						</xs:complexType>
					</xs:element>
					<xs:element name="Country" type="Country"/>
					<xs:element name="Owner" type="Player" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="HousesNumber" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Asset">
		<xs:complexContent>
			<xs:extension base="CellBase">
				<xs:sequence>
					<xs:element name="Group" type="Assets"/>
					<xs:element name="GroupToll" type="xs:int"/>
					<xs:element name="Owner" type="Player" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CellBase">
		<xs:sequence>
			<xs:element name="Price" type="xs:int" minOccurs="0"/>
			<xs:element name="PassToll" type="xs:int" minOccurs="0"/>
			<xs:element name="LandToll" type="xs:int" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:int" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="City"/>
					<xs:enumeration value="Service"/>
					<xs:enumeration value="Jail"/>
					<xs:enumeration value="GotoJail"/>
					<xs:enumeration value="Parking"/>
					<xs:enumeration value="Chance"/>
					<xs:enumeration value="Community Chest"/>
					<xs:enumeration value="Go"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Buyable" type="xs:boolean" use="required"/>
		<xs:attribute name="Owned" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="Player">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="OwnedCells">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="Cell" type="CellBase"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="OwnedCards">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="Card" type="BonusCard"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Money" type="xs:int" use="required"/>
		<xs:attribute name="BoardPosition" type="xs:int" use="required"/>
		<xs:attribute name="IsInGame" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:element name="CardsDeck">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="BonusCard" type="BonusCard"/>
			</xs:sequence>
			<xs:attribute name="Type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Community Chest"/>
						<xs:enumeration value="Chance"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="BonusCard">
		<xs:sequence>
			<xs:element name="Message" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:int" use="required"/>
		<xs:attribute name="Type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Money"/>
					<xs:enumeration value="Jail Pass"/>
					<xs:enumeration value="MoveTo"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Amount" type="xs:int"/>
		<xs:attribute name="Bank" type="xs:boolean"/>
		<xs:attribute name="MoveTo">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Chance"/>
					<xs:enumeration value="Community Chest"/>
					<xs:enumeration value="Jail (Free Pass)"/>
					<xs:enumeration value="Go"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="GetGoCash" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="Country">
		<xs:complexContent>
			<xs:extension base="Group">
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="City" type="CellBase"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Group">
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Assets">
		<xs:complexContent>
			<xs:extension base="Group">
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="Asset" type="CellBase"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== Robi07/monopolybb/MonopolyUI/src/configuration/ChanceDeck.xml
<?xml version="1.0" encoding="UTF-8"?>
<CardsDeck Type="Chance" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MonopolySchema2.xsd">
	<BonusCard ID="1" Type="Money" Bank="true" Amount="20">
		<Message>You won the sehug contest of Rosh-Hayin get 20 shekels from the Bank</Message>
	</BonusCard>
	<BonusCard ID="2" Type="Money" Bank="false" Amount="100">
		<Message>For your marriage get 100 shekels from each player</Message>
	</BonusCard>
	<BonusCard ID="3" Type="Money" Bank="true" Amount="200">
		<Message>You won the European Dance Dance Revolution contest get 200 shekels from the Bank to buy your pride back</Message>
	</BonusCard>
	<BonusCard ID="4" Type="Money" Bank="false" Amount="0">
		<Message>You wrote an amazing Monoply game in Java, get tons of respect from all the other players!</Message>
	</BonusCard>
	<BonusCard ID="5" Type="Money" Bank="false" Amount="50">
		<Message>Sing a Britney Spears song and get 50 shekels from each player</Message>
	</BonusCard>
	<BonusCard ID="6" Type="Jail Pass">
		<Message>Keep this out of jail pass, it might come in handy!</Message>
	</BonusCard>
	<BonusCard ID="7" Type="MoveTo" MoveTo="Chance" GetGoCash="true">
		<Message>Feeling lucky? Move to the next 'Chance' cell and draw another card!</Message>
	</BonusCard>
	<BonusCard ID="8" Type="MoveTo" MoveTo="Go" GetGoCash="true">
		<Message>Lucky You. Move To GO square</Message>
	</BonusCard>
</CardsDeck>

=== Robi07/monopolybb/MonopolyWSSErver/src/configuration/CommunityChestDeck.xml
<?xml version="1.0" encoding="UTF-8"?>
<CardsDeck Type="Community Chest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MonopolySchema2.xsd">
	<BonusCard ID="1" Type="Money"  Bank="true" Amount="500">
		<Message>You were caught driving in red light - pay 500 shekels to the Bank</Message>
	</BonusCard>
	<BonusCard ID="2" Type="Money" Bank="false" Amount="50">
		<Message>You are buying beer for your friends for your divorce - pay 50 shekels for each player</Message>
	</BonusCard>
	<BonusCard ID="3" Type="Money" Bank="true" Amount="300">
		<Message>You have just found out you are playing against a bunch of midgets. Donate 300 shekels to the 'How High' Association for Midgets' Self Esteem (Bank)</Message>
	</BonusCard>
	<BonusCard ID="4" Type="Money" Bank="false" Amount="60">
		<Message>You're feeling way too rich! Pay 60 shekels to each player</Message>
	</BonusCard>
	<BonusCard ID="5" Type="MoveTo" MoveTo="Jail (Free Pass)" GetGoCash="false">
		<Message>You have failed to finish your java assignment, go to jail!</Message>
	</BonusCard>
	<BonusCard ID="6" Type="MoveTo" MoveTo="Community Chest" GetGoCash="false">
		<Message>Feeling lucky? Move to the next community chest cell</Message>
	</BonusCard>
</CardsDeck>
